const RESPONSE_CONFIG = {
  SUCCESS: {
    GET_MSG: 'Data received successfully',
    RAFFLE_CREATION_SUCCESS: 'Your raffle was created!',
    UPDATE_MSG: 'Data updated successfully',
    REDEEM_CODE_MSG: 'Code redeemed successfully',
    REGISTERED_IN: "You're now registered",
    LOGGED_IN: "You're now logged",
    TICKET_BUY_SUCCESS: "You're now in!",
    WALLET_VERIFICATION_STARTED: 'Wallet verification started...',
    WALLET_VERIFICATION_SUCCESS: 'Your wallet is now verified',
  },

  ERROR: {
    TYPES: {
      Unknown: 'Unknown',
      Generic: 'Generic',
      Database: 'Database',
      Redis: 'Redis',
      Authorization: 'Authorization',
      Deposit: 'Deposit',
      Game: 'Game',
      ExternalAPIs: 'External APIs',
      Register: 'Register',
      UserInfo: 'User Info',
      EnvVariablesMissing: 'Environment Variables Missing',
      RabbitMQ: 'RabbitMQ',
      WalletVerification: 'Wallet Verification',
    },

    SYSTEM_ERROR_MSGS: {
      DOCUMENT_NOT_IN_DB_MSG: 'Document not in DB',
      INVALID_PAYLOAD: 'Invalid payload',
      REDIS: 'Error at redis',
      ENV_VARIABLES_MISSING: 'You forgot some environment variables: ',
      UNAVAILABLE_AUTH_METHOD: 'Unavailable auth method',
      FORGED_WEBHOOK: 'Webhook forged',
      RAFFLE_LOST: 'System lost a specific raffle',
      INVALID_JWT: 'INVALID_JWT',
      GOOGLE_OAUTH_SYSTEM: 'Something went wrong with GoogleOAuthSystem',
      SUSPICIOUS_AUTH: 'Something suspicious with user authentication',
      BLACKLISTED_TOKEN: 'Authentication with blacklisted token by user: ',
    },

    CLIENT_ERROR_MSGS: {
      GENERIC_MSG: `Something went wrong. We're fixing it!`,
      AUTH_MSG: 'Unauthorized',
      INVALID_USERNAME: 'Username or password invalid',
      INVALID_PASSWORD: 'Username or password invalid',
      JWT_EXPIRED: 'Token expired',
      CODE_NOT_FOUND: 'Invalid code',
      CODE_USAGE_LIMIT: 'Code reached limit',
      CODE_ALREADY_USED: 'Code already used',
      USERNAME_ALREADY_EXISTS: 'Username already exists',
      EMAIL_ALREADY_EXISTS: 'E-mail already exists',
      EMAIL_NOT_UPDATABLE: 'E-mail could not be updated',
      USER_NOT_FOUND: 'User not found',
      INSUFFICIENT_BALANCE: 'Insufficient balance',
      GAME_ALREADY_FINISHED: 'Game already finished',
      INVALID_LOGIN_METHOD: 'Account used a different method to register',
      TICKET_ALREADY_TAKEN: 'Ticket already taken',
      QUANTITY_EXCEEDS_AVAILABLE_TICKETS: 'Quantity exceeds available tickets',
      WALLET_ALREADY_VERIFIED: 'Wallet already verified',
      WALLET_VERIFICATION_FAILED: 'Wallet verification failed',
      UNAVAILABLE_NETWORK: 'This network is currently unavailable',
      UNAVAILABLE_TOKEN: 'This token is currently unavailable',
      WALLET_ALREADY_IN_USE: 'Wallet already in use',
    },
  },
};

export { RESPONSE_CONFIG };
