const RESPONSE_CONFIG = {
  SUCCESS: {
    GET_MSG: 'Data received successfully',
    RAFFLE_CREATION_SUCCESS: 'Your raffle was created!',
    UPDATE_MSG: 'Data updated successfully',
    REDEEM_CODE_MSG: 'Code redeemed successfully',
    REGISTERED_IN: "You're now registered",
    LOGGED_IN: "You're now logged",
    TICKET_BUY_SUCCESS: "You're now in!",
    WALLET_VERIFICATION_STARTED: 'Wallet verification started...',
    WALLET_VERIFICATION_SUCCESS: 'Your wallet is now verified',
  },

  ERROR: {
    NAMES: {
      /* CLIENT ERRORS */
      WalletAlreadyInUseError: 'WalletAlreadyInUseError',
      GenericError: 'GenericError',
      UserNotFound: 'UserNotFound',
      AuthError: 'AuthError',
      InvalidUsernameError: 'InvalidUsernameError',
      InvalidPasswordError: 'InvalidPasswordError',
      InvalidLoginMethodError: 'InvalidLoginMethodError',
      JWTExpiredError: 'JWTExpiredError',
      UsernameAlreadyExistsError: 'UsernameAlreadyExistsError',
      EmailAlreadyExistsError: 'EmailAlreadyExistsError',
      UserUpdateInfoError: 'UserUpdateInfoError',
      WalletVerificationError: 'WalletVerificationError',
      WalletAlreadyVerifiedError: 'WalletAlreadyVerifiedError',
      CodeNotFoundError: 'CodeNotFoundError',
      CodeAlreadyUsedError: 'CodeAlreadyUsedError',
      CodeUsageLimitError: 'CodeUsageLimitError',
      InsufficientBalanceError: 'InsufficientBalanceError',
      GameAlreadyFinishedError: 'GameAlreadyFinishedError',
      TicketAlreadyTakenError: 'TicketAlreadyTakenError',
      QuantityExceedsAvailableTicketsError: 'QuantityExceedsAvailableTicketsError',
      TicketBuyLimitReachedError: 'TicketBuyLimitReachedError',

      /* BALANCE UPDATE ERRORS */
      ProcessCreateRaffleItemError: 'ProcessCreateRaffleItemError',
      ProcessBuyRaffleTicketItemError: 'ProcessBuyRaffleTicketItemError',
      ProcessPayWinnersItemError: 'ProcessPayWinnersItemError',
      ProcessDepositError: 'ProcessDepositError',
      ProcessRefundError: 'ProcessRefundError',
      UnavailableNetworkError: 'UnavailableNetworkError',
      UnavailableTokenError: 'UnavailableTokenError',

      /* SYSTEM ERRORS */
      DatabaseError: 'DatabaseError',
      UnavailableAuthMethod: 'UnavailableAuthMethod',
      UnexpectedDatabaseError: 'UnexpectedDatabaseError',
      DocumentNotFoundError: 'DocumentNotFoundError',
      InvalidPayloadError: 'InvalidPayloadError',
      RedisError: 'RedisError',
      YoutubeAPIError: 'YoutubeAPIError',
      RegisterError: 'RegisterError',
      EnvVariablesMissingError: 'EnvVariablesMissingError',
      UnknownError: 'UnknownError',
      ForgedWebhookError: 'ForgedWebhookError',
      CreateRaffleUnexpectedError: 'CreateRaffleUnexpectedError',
      RaffleLostError: 'RaffleLostError',
      InvalidJWTError: 'InvalidJWTError',
      GoogleOAuthSystemError: 'GoogleOAuthSystemError',
      SuspiciousAuthError: 'SuspiciousAuthError',
      InvalidRefreshToken: 'InvalidRefreshToken',
      BlacklistedTokenError: 'BlacklistedTokenError',
    },

    SYSTEM_ERROR_MSGS: {
      DOCUMENT_NOT_IN_DB_MSG: 'Document not in DB',
      INVALID_PAYLOAD: 'Invalid payload',
      REDIS: 'Error at redis',
      ENV_VARIABLES_MISSING: 'You forgot some environment variables: ',
      UNAVAILABLE_AUTH_METHOD: 'Unavailable auth method',
      FORGED_WEBHOOK: 'Webhook forged',
      RAFFLE_LOST: 'System lost a specific raffle',
      CREATE_RAFFLE: 'Something went wrong creating a raffle',
      INVALID_JWT: 'INVALID_JWT',
      GOOGLE_OAUTH_SYSTEM: 'Something went wrong with GoogleOAuthSystem',
      SUSPICIOUS_AUTH: 'Something suspicious with user authentication',
      BLACKLISTED_TOKEN: 'Authentication with blacklisted token by user: ',
    },

    CLIENT_ERROR_MSGS: {
      GENERIC_ERROR_MSG: `Something went wrong. We're fixing it!`,
      AUTH_MSG: 'Unauthorized',
      INVALID_USERNAME: 'Username or password invalid',
      INVALID_PASSWORD: 'Username or password invalid',
      JWT_EXPIRED: 'Token expired',
      CODE_NOT_FOUND: 'Code not found',
      CODE_USAGE_LIMIT: 'Code reached limit',
      CODE_ALREADY_USED: 'Code already used',
      USERNAME_ALREADY_EXISTS: 'Username already exists',
      EMAIL_ALREADY_EXISTS: 'E-mail already exists',
      EMAIL_NOT_UPDATABLE: 'E-mail could not be updated',
      USER_NOT_FOUND: 'User not found',
      INSUFFICIENT_BALANCE: 'Insufficient balance',
      GAME_ALREADY_FINISHED: 'Game already finished',
      INVALID_LOGIN_METHOD: 'Account used a different method to register',
      TICKET_ALREADY_TAKEN: 'Ticket already taken',
      QUANTITY_EXCEEDS_AVAILABLE_TICKETS: 'Quantity exceeds available tickets',
      WALLET_ALREADY_VERIFIED: 'Wallet already verified',
      WALLET_VERIFICATION_FAILED: 'Wallet verification failed',
      UNAVAILABLE_NETWORK: 'This network is currently unavailable',
      UNAVAILABLE_TOKEN: 'This token is currently unavailable',
      WALLET_ALREADY_IN_USE: 'Wallet already in use',
      TICKET_BUY_LIMIT_REACHED: 'Ticket limit reached',
    },
  },
};

export { RESPONSE_CONFIG };
